name: YC function deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Use node.js v22
        uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy YC function
        id: sls-func
        uses: yc-actions/yc-sls-function@v5
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: 'b1g46471u05u2sfq1brd'
          function-name: 'yc-filter-api-fn'
          runtime: 'nodejs22'
          execution-timeout: '600'
          memory: '1024Mb'
          entrypoint: 'dist/index.handler'
          include: |
            ./dist
            package.json
          exclude: |
            **/*.ts
      - name: Deploy YC function 2
        id: sls-func2
        uses: yc-actions/yc-sls-function@v5
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: 'b1g46471u05u2sfq1brd'
          function-name: 'yc-filter-api-fn2'
          runtime: 'nodejs22'
          execution-timeout: '600'
          memory: '1024Mb'
          entrypoint: 'dist/index.handler'
          include: |
            ./dist
            package.json
          exclude: |
            **/*.ts